#!/usr/bin/env bash
#the trap command in use
#+ syntax trap [ action ] command

trap "echo \"I am invincible!!!\"" SIGTERM

x=1

while [ "${x}" -gt 0]
do
    echo "To infinity and beyond"
    sleep 2
    ((x++))
done
