#!/usr/bin/env bash
# displays the content of /etc/password
#+ displays username, user id, homedirectory path of the user

while read -r passwd; do
    echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
