#!/usr/bin/env bash
# displays 4 and then bad luck from China for the 4th loop iteration
#+ displays 9 and then bad luck from Japan for the 9th loop iteration
#+ displays 17 and then bad luck from Italy for the 17th loop iteration

x=1

while [ "${x}" -lt 21 ]
do
    echo "${x}"
    case "${x}" in
    4)
        echo "bad luck from china"
    ;;
    9)
        echo "bad luck from Japan"
    ;;
    17)
        echo "bad luck from italy"
    ;;
    esac
    ((x++))
done