#!/usr/bin/env bash
#display hours from 0 to 12
#display minutes from 1 to 59

hours=-1
minutes=60

while [ "${hours}" -lt 13 ]
do
    if [ "${minutes}" -eq 60 ]
    then
        ((hours++))
        if [ "${hours}" -eq 13 ]
        then
            break
        fi
        echo "Hour: ${hours}"
        minutes=1
    fi
    echo "${minutes}"
    ((minutes++))
done
