#!/usr/bin/env bash
# program gives info about a certain file

filename="school"

if [ -e "${filename}" ]
then
    echo "${filename} file exists"
    if [ -s "${filename}" ]
    then
        echo "${filename} file is not empty"
    else
        echo "${filename} is empty"
    fi

    if [ -f "${filename}" ]
    then
        echo "${filename} is a regular file"
    fi
else
    echo "${filename} does not exist"

fi
